### ISSUE TITLE
Npc giving off an error

### ISSUE THREAD

**Issue by unclear125** [TomDotBat/svault#3]
Whenever i spawn the npc it creates this error

[svault] addons/svault/lua/entities/svault_npc/cl_init.lua:20: bad argument #1 to 'GetTextSize' (string expected, got nil)
  1. GetTextSize - [C]:-1
   2. drawOverhead - addons/svault/lua/entities/svault_npc/cl_init.lua:20
    3. unknown - addons/svault/lua/entities/svault_npc/cl_init.lua:47 (x1401)

**Comment by TomDotBat** [comment]
The NPC was never fully implemented so this is expected.
